# Generated by Django 4.0.6 on 2022-07-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateField(verbose_name='Thời gian bắt đầu')),
                ('color1', models.TextField(help_text='Màu chính cho sự kiện', max_length=8, verbose_name='Màu 1')),
                ('color2', models.TextField(help_text='Màu chính cho sự kiện, đậm hơn màu 1', max_length=8, verbose_name='Màu 2')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
    ]
