# Generated by Django 4.0.6 on 2022-07-27 16:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color1',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Màu chính cho sự kiện', image_field=None, max_length=8, samples=None, verbose_name='Màu 1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='color2',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Màu chính cho sự kiện, đậm hơn màu 1', image_field=None, max_length=8, samples=None, verbose_name='Màu 2'),
        ),
    ]
