# Generated by Django 4.0.6 on 2022-07-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_event_activate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['active', 'title']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['active']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='activate',
            new_name='active',
        ),
    ]
